### ISSUE TITLE
bug input stream

### ISSUE THREAD

**Issue by davvore33** [modulebaan/Sailfinder#3]
Return value of PyObject call is NULL: Traceback (most recent call last):

  File "/usr/share/harbour-sailfinder/qml/pages/tinder.py", line 520, in loadAboutMatch
    pyotherside.send('getMatchCommonInterests', matches[matchNumber].user.common_interests)

  File "/usr/share/harbour-sailfinder/qml/pages/pynder/models/user.py", line 49, in common_interests
    return [p for p in self._data['common_interests']]

KeyError: 'common_interests'

**Comment by davvore33** [comment]
set a try check

**Comment by modulebaan** [comment]
Issue is fixed in V0.9
